"""add_login_log_table

Revision ID: 462c26c83d28
Revises: 7ffd5b602f56
Create Date: 2025-08-21 16:04:00.067135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462c26c83d28'
down_revision = '7ffd5b602f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_logs')
    # ### end Alembic commands ###
